FROM jenkins/jenkins:2.150.3
USER root
RUN  mkdir /var/log/jenkins && chown -R  jenkins:jenkins /var/log/jenkins
RUN  mkdir /var/cache/jenkins && chown -R jenkins:jenkins /var/cache/jenkins
COPY ./plugins /tmp/plugins
COPY --chown=jenkins:jenkins ./preconfigure/ /usr/share/jenkins/ref/init.groovy.d
USER jenkins
ENV  JAVA_OPTS="-Xmx2048m -Djenkins.install.runSetupWizard=false"
ENV  JENKINS_OPTS=" --handlerCountMax=150 --logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war"
EXPOSE 8080 50000
RUN /usr/local/bin/install-plugins.sh < /tmp/plugins

